### ISSUE TITLE
Checkbox issue

### ISSUE THREAD

**Issue by Qrzysio** [domainmod/domainmod#61]
There is an issue with checkboxes while editing a domain + would be useful to add a calendar when we choose Expiry Date.

![image](https://user-images.githubusercontent.com/13356480/36307009-19ecc7f8-1355-11e8-95ac-02474e733712.png)

**Comment by RogueScholar** [comment]
I'm encountering the same issue, using Vivaldi 1.15.1111.3 on Kubuntu 18.04.

The calendar is a good idea too, though I'm more of a keyboard warrior myself so it would rank as a low priority item in my book.

**Comment by chetcuti** [comment]
The issue with the checkboxes is usually due to either JavaScript being disabled, or some sort of an ad/content blocker being installed that's messing with the code ([user guide entry](https://domainmod.org/docs/userguide/troubleshooting/#javascript)).

Regarding the calendar picker, I agree that this would be handy, and it's actually been on the list to implement for a while now. I also want to replace the calendar picker that's used for the Advanced Filtering on the main domains page, as the one that's currently being used on there is a bit finicky.

**Comment by Qrzysio** [comment]
I've spent some time to solve the problem. What I found is the file `domains/edit.php?did=XXXX` ends up unexpectedly.  The last line of source code is `</form>`. There are no scripts included and no `</html>` tag. 
Try to edit a domain and check if the source code is completed. I cannot expand sidebar menu because of lack `app.min.js` etc. On other pages, such as the dashboard or domain list, scripts are working properly. 

Maybe this error occurs only when we add some custom inputs. I hope this will help you to fix it. Thank you.

**Comment by chetcuti** [comment]
Hmm, very odd. So when you edit a domain and view the source code `</form>` is literally the last thing that gets displayed? Everything after that gets cutoff and is simply gone?

Do you have any [custom domain fields](https://domainmod.org/docs/userguide/administration/#custom-fields) created?

Do you use the built-in [Data Warehouse](https://domainmod.org/docs/userguide/data-warehouse/)? And if so, does this problem only happen when you're editing a domain that has data saved in the Data Warehouse, or all domains?

I've never seen anything like this before, and it's a very odd issue, so it may not be easy to troubleshoot. If you would be ok with me seeing your data, I think the fastest way to solve this would be to import your data into my development environment and see if I can replicate the issue. If I can, I'm almost positive I can figure out what's going on here.

If this is something you would be open to, please see our [Hands-on Help Request](https://domainmod.org/request/) page for more information.

**Comment by Qrzysio** [comment]
It is exactly as you said. I do not use Data Warehouse, but I have a few custom domain fields. I will update to the latest version first and then will let you know if the issue still persists.

**Comment by chetcuti** [comment]
@Qrzysio, very odd indeed. Definitely let me know if the newest version has the same issue. Also, do any of your custom domain fields have special characters in them? (either the fields themselves or the data). If you're comfortable with me seeing your custom domain fields, if you can export the list and email it to support@domainmod.org I'll re-create them on my end and see if they work for me.

@Qrzysio & @RogueScholar, I've now implemented a calendar/date picker for every expiration field (both Domains & SSLs), and I've updated the date range picker on the main Domain and SSL pages, as well as on each of the reports, to be more user-friendly. These will both be in the next release.

**Comment by Qrzysio** [comment]
Hi,

I have updated the script to the latest version. Unfortunately, this issue persists. Adding a domain works well, but while editing the page is not fully loading. The last HTML tag is `</form>` (after `Save` button).

Look at the custom fields config and compare views between adding and editing a domain.

## Custom domain fields
![01 custom domain fields](https://user-images.githubusercontent.com/13356480/38985961-3e581952-43cb-11e8-916c-e6d08b2876ef.png)

## Edit domain
![02 edit domain](https://user-images.githubusercontent.com/13356480/38985974-4b88bce4-43cb-11e8-94fb-79587f09b426.png)

## Add domain
![03 add domain](https://user-images.githubusercontent.com/13356480/38985975-4ba58162-43cb-11e8-8c50-a2052893b837.png)

**Comment by Qrzysio** [comment]
I'm happy to see the new version of domainmod. However, this issue still remains.

**Comment by ste10** [comment]
I confirm,
even after the last update the problem persists. :(

**Comment by ste10** [comment]
I confirm, I have updated domainmod, but the problem persists. :(

**Comment by ste10** [comment]
Any update???

**Comment by Qrzysio** [comment]
I confirm, it has been fixed and after update to v4.11 edit page works properly. Calendar and checkboxes are working well. Thank you!

**Comment by chetcuti** [comment]
Closing issue, as this was fixed in v4.11.
